### ISSUE TITLE
Popover is not really accessible

### ISSUE THREAD

**Issue by ghost** [teamon/headless#1]
Hi,

I would expect to be able to operate the popover with the keyboard, as stated here:
https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/

But it does not seems the case (I am trying the popover here):
https://headless.fly.dev/Headless-Demo-DaisyUI-popover-1

Do you plan to support keyboard navigation?

Cheers!

**Comment by teamon** [comment]
Hey, this project is in a very early stage.
The demo components are just for demonstration on how to use `use_*` components.

The `use_popover/1` components is concerned only about showing and hiding the overlay - it does not care about the contents of the popover. 

To make a fully accessible dropdown menu component one could build on top of `use_popover/1`. 

There might be a `Headless.use_dropdown/1` component in the future.
